name: Elixir CI

on:
  push:
    branches:
      - master
      - dev/*
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test on Elixir ${{matrix.elixir}} / OTP ${{matrix.otp}}
    strategy:
      matrix:
        elixir: [1.7.0, 1.8.0, 1.9.0, 1.10.0]
        otp: [20.0, 21.0, 22.0, 23.0]
        exclude:
          - elixir: 1.10.0
            otp: 20.0
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          elixir-version: ${{matrix.elixir}}
          otp-version: ${{matrix.otp}}
      - run: mix deps.get
      - run: mix test
